{% set name = "AWSIoTPythonSDK" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 51d46c3d6e31ca8ef4ef4cfbbaf86361cc7b89b937c7ee6dc2158636e305cb5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - AWSIoTPythonSDK
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-iot-device-sdk-python.git
  summary: SDK for connecting to AWS IoT using Python.
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - Rama2209
