{% set name = "AWSIoTPythonSDK" %}
{% set version = "1.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 9db00c37b5ff18ac63a81f4b514e4c9d655c022e14c629447a686d873d1dcffc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - AWSIoTPythonSDK
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-iot-device-sdk-python.git
  summary: SDK for connecting to AWS IoT using Python.
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - Rama2209
