{% set name = "AWSIoTPythonSDK" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/AWSIoTPythonSDK-{{ version }}.tar.gz
  sha256: c66ec16a9cb7837d515431e2c75835a4adbdd578851e19e788017830afcc9683

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - AWSIoTPythonSDK
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-iot-device-sdk-python.git
  summary: SDK for connecting to AWS IoT using Python.
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - Rama2209
